version: '2'
services:
  app:
    container_name: sample_docker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '10001:10001'
    volumes:
        - .:/var/www
    working_dir: /var/www
    command: npm start
    environment:
      NODE_ENV: local
